name: todo service

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: make composer-install
      working-directory: todo
    - name: stan
      run: make stan
    - name: test
      run: make test
      working-directory: todo
    - name: spec-coverage
      run: make spec-coverage
      working-directory: todo
    - name: upload todo coverage
      uses: actions/upload-artifact@v1
      with:
        name: todo-coverage
        path: todo/coverage