name: todo service

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

#     - name: Validate composer.json and composer.lock
#       run: composer validate
#       working-directory: user

    - name: Install dependencies
      run: make composer-install
      working-directory: todo

    - name: test
      run: make test
      working-directory: todo

    - name: spec-coverage
      run: make spec-coverage
      working-directory: todo

    - name: Upload math result for job 2
      uses: actions/upload-artifact@v1
      with:
        name: todo-coverage
        path: todo/coverage

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
